### ISSUE TITLE
xee resolution export != native resolution

### ISSUE THREAD

**Issue by Meursault-Mq** [google/Xee#173] opened 2024-09-11 09:53 UTC
Hello, 

When loading "NASA/GDDP-CMIP6" image with xee, the output resolution is 1° whereas when using Javascript GEE editor the native resolution is 0.25.

``import ee ``
``coords=[
        [-125,30],
    [-113,30],
    [-113,42],
    [-125,42],
        [-125,32]
    ]
California_bbox=ee.Geometry.Polygon([coords]
)
``

``imageCollection=ee.ImageCollection("NASA/GDDP-CMIP6")\
                        .filter(ee.Filter.eq("model", "GFDL-ESM4"))\
                        .filter(ee.Filter.eq("scenario","historical"))\
                        .filterDate('2012-01-01','2012-03-31')\
                        .select('tas','pr')``

``ds=xarray.open_dataset(imageCollection, engine='ee',crs="EPSG:4326",geometry=California_bbox)
``
``ds``
  <xarray.Dataset>
  Dimensions:  (time: 3, lon: 12, lat: 12)
  Coordinates:
  * lon      (lon) float64 -124.5 -123.5 -122.5 -121.5 ... -115.5 -114.5 -113.5
  * lat      (lat) float64 30.5 31.5 32.5 33.5 34.5 ... 37.5 38.5 39.5 40.5 41.5
  * time     (time) datetime64[ns] 2012-01-31 2012-02-29 2012-03-31
  Data variables:
    tas      (time, lon, lat) float32 nan nan nan nan ... 277.6 279.5 277.5
    pr       (time, lon, lat) float32 nan nan nan ... 6.862e-06 7.235e-06
  Attributes:
    crs:      EPSG:4326 

It seems like in the absence of scale parameter it scales back to 1° instead of the original 0.25°

When looking at the dimensions of the matrice (once I clipped the image ) in GEE editor, with the same bbox I have 50 x 51 matrice which is ~4 times the dimensions of the xarray.Dataset and the Nominal scale is 27 km as the description said.

I could use scale = 0.25 in open_dataset method, and if I understood correctly it would output a 0.25°-resolution dataset as the EPSG = 4326. 
But I don't really know if the data has been altered by the scale factor ( by some resampling before hand or else).

Thanks for your help

**Comment by jdbcode** [comment] 2024-09-17 17:58
If you are not providing `projection`, `scale`, or `crs`, xee will make a best effort to fetch them or fall back to `EPSG:4326` with 1-degree scale. The CMIP6 data have 'EPSG:4326' CRS already (and you've defined it as such), but since you did not specify `scale`, it uses the default (see [here](https://github.com/google/Xee/blob/27eda3efc8e7f29039db5a5c5ba48951937e1972/xee/ext.py#L253) and [here](https://github.com/google/Xee/blob/27eda3efc8e7f29039db5a5c5ba48951937e1972/xee/ext.py#L117)).

If you want to ensure that the returned array has the same crs and scale as the original data, without any resampling, you should either explicitly provide arguments to the `crs` and `scale` parameters based on a representative image e.g.,

```py
ee_projection = imageCollection.first().projection().getInfo()
crs = ee_projection['crs']
scale = ee_projection['transform'][0]

ds = xarray.open_dataset(
    imageCollection,
    engine='ee',
    crs=crs,
    scale=scale,
    geometry=California_bbox
)
```
...or provide a representative `ee.Projection` from an image in the collection and Xee will pull the `crs` and `scale` (from the transform) from the image (see [here](https://github.com/google/Xee/blob/27eda3efc8e7f29039db5a5c5ba48951937e1972/xee/ext.py#L235) and [here](https://github.com/google/Xee/blob/27eda3efc8e7f29039db5a5c5ba48951937e1972/xee/ext.py#L258)).

```py
ee_projection = imageCollection.first().projection().getInfo()
crs = ee_projection['crs']
scale = ee_projection['transform'][0]

ds = xarray.open_dataset(
    imageCollection,
    engine='ee',
    projection=ee_projection,
    geometry=California_bbox
)
```

Closing for now. If something does not seem to be working as intended or you'd like to discuss further, please reopen.

**Closed by jdbcode** 2024-09-17 17:58 UTC
